---
- hosts: all
  gather_facts: no
  tasks:
    - name: archive container image as a tarball
      docker_image:
        name: democontainer:v1.0
        archive_path: /root/hello_devops_container.tar
        source: pull
        state: present
    - name: fetch archived image
      fetch:
        src: /root/hello_devops_container.tar
        dest: ./hello_devops_container.tar
        flat: true