
namespace: community
name: docker
version: 3.5.0
readme: README.md
authors:
  - Ansible Docker Working Group
description: Modules and plugins for working with Docker
license:
  - GPL-3.0-or-later
  - Apache-2.0
#license_file: COPYING
tags:
  - docker
repository: https://github.com/ansible-collections/community.docker
#documentation: https://github.com/ansible-collection-migration/community.REPO_NAME/tree/main/docs
homepage: https://github.com/ansible-collections/community.docker
issues: https://github.com/ansible-collections/community.docker/issues
build_ignore:
# https://docs.ansible.com/ansible/devel/dev_guide/developing_collections.html#ignoring-files-and-folders
  - .gitignore
  - changelogs/.plugin-cache.yaml