  collections: community.docker

    - name: ensure a container is running
      docker_container:
        name: hello-world-ansible
        state: started
        image: "${{ secrets.DOCKERHUB_USERNAME }}/hello-world-ansible:latest"
        pull: true
        ports:
          - "3000:3000"

    - name: ensure a container is running
      docker_container:
        name: hello-devops
        state: started
        image: "${{ secrets.DOCKERHUB_USERNAME }}/hello-devops:latest"
        pull: true
        ports:
          - "4000:4000"

    - name: ensure a container is running
      docker_container:
        name: hello-world
        state: started
        image: "${{ secrets.DOCKERHUB_USERNAME }}/hello-world:latest"
        pull: true
        ports:
          - "6000:6000"