- hosts: all
  become: true

  tasks:
    - name: log into docker hub registry
      docker_login:
        email: ${{ secrets.DOCKERHUB_EMAIL }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: ensure a container is running
      docker_container:
        name: hello-world
        state: started
        image: "${{ secrets.DOCKERHUB_USERNAME }}/hello-world:latest"
        pull: true
        ports:
          - "3000:3000"