name: deploy ansible

on:
  workflow_run:
    workflows: ["Python package"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v2
    - name: Lint Ansible Playbook
      uses: ansible/ansible-lint-action@main
      with:
        path: ansible-challenge/ansible_files
  deployAnsible:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./.github/actions/ansible
      with: 
        playbook: ansible-challenge/ansible_files/playbook.yml
        inventory: localhost