name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
      - 
        uses: actions/checkout@v3
      - 
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: capstone_project/hello-world/package-lock.json
      - 
        run: npm install
        working-directory: capstone_project/hello-world/src
      -  
        run: npm test
        working-directory: capstone_project/hello-world/src

      -
        name: Set up Docker
        uses: crazy-max/ghaction-setup-docker@v1       
      - 
        uses: actions/checkout@v3
      - 
        name: Build the Docker image
        run: docker build . --file capstone_project/hello-world/Dockerfile --tag hello-world:latest
        
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./capstone_project/hello-world/Dockerfile
          push: true

      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - 
        name: Pulling local container image
        run: docker image pull ${{ secrets.DOCKERHUB_USERNAME }}/hello-world:latest

      - 
        name: Pushing container image from pull
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/hello-world:latest http://localhost/hello
        
      -
        name: List docker images
        run: docker images

        