# YAML workflow name
name: Docker Image CI

# When YAML will load (when main branch is pushed to)
on:
  push:
    branches: [ "main" ]

on: workflow_dispatch


# Jobs
jobs:

  build:
    runs-on: ubuntu-latest
    
    # When the push is made, setup the node testing environment (to keep large file sizes from node_modules OFF main development computer)
    steps:
      - 
        uses: actions/checkout@v3
      # Set up Docker for GitHub Actions environment
      -
        name: Set up Docker
        uses: crazy-max/ghaction-setup-docker@v1      
        
      # Check out branch and log into Docker Hub (for Docker file upload)
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./capstone_project/hello-world/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/hello-world:latest

      # See successful image locally created by Docker
      -
        name: List docker images
        run: docker images -a

      # See current image locallycreated by Docker
      -
        name: Current docker images
        run: docker ps

      # See current image locallycreated by Docker
      -
        name: Start NPM 
        run: docker ps